spring:
  application:
    name: agenda
  datasource:
    url: jdbc:postgresql://localhost:5434/agenda
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080